import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:jobkarlite/view/page/fresher_card.dart';
import 'package:jobkarlite/viewmodel/user_controller.dart';

import '../component/input_box.dart';

class FresherList extends StatefulWidget {
  const FresherList({Key? key}) : super(key: key);

  @override
  State<FresherList> createState() => _FresherListState();
}

class _FresherListState extends State<FresherList> {
  final searchController = TextEditingController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[200],
      appBar: AppBar(
        automaticallyImplyLeading: false,
        titleSpacing: 10,
        title: Text("Fresher",style: UserController.style1),
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: ListView(
          physics: const BouncingScrollPhysics(),
          children: [
            InputBox(
              title: 'Search',
              filter: () {},
              icon: CupertinoIcons.search,
              controller: searchController,
            ),
            const SizedBox(height: 8),
            FresherCard(
                userName: 'Amit Kumar',
                userEmail: 'amit@gmail.com',
                skill: 'Java Android Development',
                testScore: '30/21',
                callTap: (){},
                chatTap: (){},
                favouriteTap: (){},
                hireTap: (){} ,
            ),
            const SizedBox(height: 8),
            FresherCard(
              userName: 'Aradhya Sangeni',
              userEmail: 'amit@gmail.com',
              skill: 'Java Android Development',
              testScore: '30/21',
              callTap: (){},
              chatTap: (){},
              favouriteTap: (){},
              hireTap: (){} ,
            ),
            const SizedBox(height: 8),
            FresherCard(
              userName: 'Amit Kumar',
              userEmail: 'amit@gmail.com',
              skill: 'Java Android Development',
              testScore: '30/21',
              callTap: (){},
              chatTap: (){},
              favouriteTap: (){},
              hireTap: (){} ,
            ),
            const SizedBox(height: 8),
            FresherCard(
              userName: 'Aradhya Sangeni',
              userEmail: 'amit@gmail.com',
              skill: 'Java Android Development',
              testScore: '30/21',
              callTap: (){},
              chatTap: (){},
              favouriteTap: (){},
              hireTap: (){} ,
            ),
            const SizedBox(height: 8),
            FresherCard(
              userName: 'Amit Kumar',
              userEmail: 'amit@gmail.com',
              skill: 'Java Android Development',
              testScore: '30/21',
              callTap: (){},
              chatTap: (){},
              favouriteTap: (){},
              hireTap: (){} ,
            ),
            const SizedBox(height: 8),
            FresherCard(
              userName: 'Aradhya Sangeni',
              userEmail: 'amit@gmail.com',
              skill: 'Java Android Development',
              testScore: '30/21',
              callTap: (){},
              chatTap: (){},
              favouriteTap: (){},
              hireTap: (){} ,
            ),
            const SizedBox(height: 8),
            FresherCard(
              userName: 'Amit Kumar',
              userEmail: 'amit@gmail.com',
              skill: 'Java Android Development',
              testScore: '30/21',
              callTap: (){},
              chatTap: (){},
              favouriteTap: (){},
              hireTap: (){} ,
            ),
            const SizedBox(height: 8),
            FresherCard(
              userName: 'Aradhya Sangeni',
              userEmail: 'amit@gmail.com',
              skill: 'Java Android Development',
              testScore: '30/21',
              callTap: (){},
              chatTap: (){},
              favouriteTap: (){},
              hireTap: (){} ,
            ),
            const SizedBox(height: 8),
            FresherCard(
              userName: 'Amit Kumar',
              userEmail: 'amit@gmail.com',
              skill: 'Java Android Development',
              testScore: '30/21',
              callTap: (){},
              chatTap: (){},
              favouriteTap: (){},
              hireTap: (){} ,
            ),
            const SizedBox(height: 8),
            FresherCard(
              userName: 'Aradhya Sangeni',
              userEmail: 'amit@gmail.com',
              skill: 'Java Android Development',
              testScore: '30/21',
              callTap: (){},
              chatTap: (){},
              favouriteTap: (){},
              hireTap: (){} ,
            ),
            const SizedBox(height: 8),
            FresherCard(
              userName: 'Amit Kumar',
              userEmail: 'amit@gmail.com',
              skill: 'Java Android Development',
              testScore: '30/21',
              callTap: (){},
              chatTap: (){},
              favouriteTap: (){},
              hireTap: (){} ,
            ),
            const SizedBox(height: 8),
            FresherCard(
              userName: 'Aradhya Sangeni',
              userEmail: 'amit@gmail.com',
              skill: 'Java Android Development',
              testScore: '30/21',
              callTap: (){},
              chatTap: (){},
              favouriteTap: (){},
              hireTap: (){} ,
            ),
            const SizedBox(height: 8),
            FresherCard(
              userName: 'Amit Kumar',
              userEmail: 'amit@gmail.com',
              skill: 'Java Android Development',
              testScore: '30/21',
              callTap: (){},
              chatTap: (){},
              favouriteTap: (){},
              hireTap: (){} ,
            ),
            const SizedBox(height: 8),
            FresherCard(
              userName: 'Aradhya Sangeni',
              userEmail: 'amit@gmail.com',
              skill: 'Java Android Development',
              testScore: '30/21',
              callTap: (){},
              chatTap: (){},
              favouriteTap: (){},
              hireTap: (){} ,
            ),
            const SizedBox(height: 8),
            FresherCard(
              userName: 'Aradhya Sangeni',
              userEmail: 'amit@gmail.com',
              skill: 'Java Android Development',
              testScore: '30/21',
              callTap: (){},
              chatTap: (){},
              favouriteTap: (){},
              hireTap: (){} ,
            ),
            const SizedBox(height: 8),
            FresherCard(
              userName: 'Amit Kumar',
              userEmail: 'amit@gmail.com',
              skill: 'Java Android Development',
              testScore: '30/21',
              callTap: (){},
              chatTap: (){},
              favouriteTap: (){},
              hireTap: (){} ,
            ),
            const SizedBox(height: 8),
            FresherCard(
              userName: 'Aradhya Sangeni',
              userEmail: 'amit@gmail.com',
              skill: 'Java Android Development',
              testScore: '30/21',
              callTap: (){},
              chatTap: (){},
              favouriteTap: (){},
              hireTap: (){} ,
            ),
            const SizedBox(height: 8),
            FresherCard(
              userName: 'Amit Kumar',
              userEmail: 'amit@gmail.com',
              skill: 'Java Android Development',
              testScore: '30/21',
              callTap: (){},
              chatTap: (){},
              favouriteTap: (){},
              hireTap: (){} ,
            ),
            const SizedBox(height: 8),
            FresherCard(
              userName: 'Aradhya Sangeni',
              userEmail: 'amit@gmail.com',
              skill: 'Java Android Development',
              testScore: '30/21',
              callTap: (){},
              chatTap: (){},
              favouriteTap: (){},
              hireTap: (){} ,
            ),
          ],
        ),
      ),
    );
  }
}
